# Generated by Django 4.2.2 on 2023-07-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('kategori', models.CharField(choices=[('smartphone', 'smartphone'), ('aksesoris', 'aksesoris'), ('perangkat lain', 'perangkat lain')], max_length=20)),
                ('kuantitas', models.PositiveBigIntegerField()),
            ],
        ),
    ]
