# Generated by Django 4.2.2 on 2023-07-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hargam',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
